# @name login
POST {{$dotenv BASE_URL}}/auth/login
Content-Type: application/json

{
  "email": "{{$dotenv DEFAULT_EMAIL}}",
  "password": "{{$dotenv DEFAULT_PASSWORD}}"
}

###
@accessToken = {{login.response.body.accessToken}}





###
GET {{$dotenv BASE_URL}}/items
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "email": "{{$dotenv DEFAULT_EMAIL}}",
  "password": "{{$dotenv DEFAULT_PASSWORD}}"
}

###
GET {{$dotenv BASE_URL}}/dashboard
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "email": "{{$dotenv DEFAULT_EMAIL}}",
  "password": "{{$dotenv DEFAULT_PASSWORD}}"
}

###
GET {{$dotenv BASE_URL}}/loans
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "email": "{{$dotenv DEFAULT_EMAIL}}",
  "password": "{{$dotenv DEFAULT_PASSWORD}}"
}