# @name login
POST {{$dotenv BASE_URL}}/auth/login
Content-Type: application/json

{
  "email": "{{$dotenv DEFAULT_EMAIL}}",
  "password": "{{$dotenv DEFAULT_PASSWORD}}"
}

###
@accessToken = {{login.response.body.accessToken}}


###
GET {{$dotenv BASE_URL}}/admin/analytics/dashboard
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
GET {{$dotenv BASE_URL}}/admin/analytics/users/stats
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
GET {{$dotenv BASE_URL}}/admin/analytics/loans/stats
Content-Type: application/json
Authorization: Bearer {{accessToken}}
